### ISSUE TITLE
Can't instantiate Chrome WebDriver 2.30

### ISSUE THREAD

**Issue by rmpestano** [arquillian/arquillian-extension-drone#105]
##### Issue Overview

When I run the tests using webdriver 2.30 or 2.31 I got the error:

```
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created exception: Chrome version must be >= 58.0.3029.0
```

There are no errors when I use chrome driver 2.29.

##### Expected Behaviour

Chrome should open

##### Current Behaviour

Chrome is not opening 

##### Steps To Reproduce

Run the provided sample project with ``` mvn clean test```

Following is a sample maven project using latest Drone with Graphene:

[cdi-crud.zip](https://github.com/arquillian/arquillian-extension-drone/files/1174394/cdi-crud.zip)

Here's the full stacktrace:

 
```
Starting ChromeDriver 2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57) on port 18942
Only local connections are allowed.
jul 25, 2017 3:26:37 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for UpdateTestResultBeforeAfter.update is null. It won't be invoked.
jul 25, 2017 3:26:37 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for UpdateTestResultBeforeAfter.update is null. It won't be invoked.

java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(Capabilities): org.openqa.selenium.SessionNotCreatedException: session not created exception: Chrome version must be >= 58.0.3029.0
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.19 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'pro-pae-4652lnx', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_121'
Driver info: driver.version: ChromeDriver

	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:166)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:81)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:41)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created exception: Chrome version must be >= 58.0.3029.0
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-83-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.19 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'pro-pae-4652lnx', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-83-generic', java.version: '1.8.0_121'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
```

Here is dependency tree:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building cdi-crud 4.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cdi-crud ---
[INFO] com.cdi.crud:cdi-crud:war:4.0.0
[INFO] +- javax:javaee-api:jar:7.0:provided
[INFO] |  \- com.sun.mail:javax.mail:jar:1.5.0:provided
[INFO] |     \- javax.activation:activation:jar:1.1:provided
[INFO] +- org.primefaces:primefaces:jar:6.1:compile
[INFO] +- com.github.adminfaces:admin-template:jar:1.0.0-RC9:compile
[INFO] |  +- org.omnifaces:omnifaces:jar:2.1:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] +- com.github.adminfaces:admin-theme:jar:1.0.0-RC9:compile
[INFO] +- org.hibernate:hibernate-core:jar:5.1.8.Final:provided
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:provided
[INFO] |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:provided
[INFO] |  +- org.javassist:javassist:jar:3.20.0-GA:provided
[INFO] |  +- antlr:antlr:jar:2.7.7:provided
[INFO] |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:provided
[INFO] |  +- org.jboss:jandex:jar:2.0.3.Final:provided
[INFO] |  +- com.fasterxml:classmate:jar:1.3.0:provided
[INFO] |  +- dom4j:dom4j:jar:1.6.1:provided
[INFO] |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:provided
[INFO] +- org.hibernate:hibernate-validator:jar:5.1.1.Final:provided
[INFO] |  \- javax.validation:validation-api:jar:1.1.0.Final:provided
[INFO] +- org.hibernate:hibernate-entitymanager:jar:5.1.8.Final:provided
[INFO] +- org.apache.deltaspike.core:deltaspike-core-impl:jar:1.8.0:compile
[INFO] +- org.apache.deltaspike.core:deltaspike-core-api:jar:1.8.0:compile
[INFO] +- org.apache.deltaspike.modules:deltaspike-jsf-module-api:jar:1.8.0:compile
[INFO] +- org.apache.deltaspike.modules:deltaspike-jsf-module-impl:jar:1.8.0:compile
[INFO] |  +- org.apache.deltaspike.modules:deltaspike-proxy-module-api:jar:1.8.0:compile
[INFO] |  \- org.apache.deltaspike.modules:deltaspike-proxy-module-impl-asm5:jar:1.8.0:runtime
[INFO] +- org.apache.deltaspike.modules:deltaspike-security-module-api:jar:1.8.0:compile
[INFO] +- org.apache.deltaspike.modules:deltaspike-security-module-impl:jar:1.8.0:runtime
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.assertj:assertj-core:jar:2.1.0:test
[INFO] +- org.arquillian.universe:arquillian-junit:pom:1.1.13.5:test
[INFO] |  +- org.arquillian.universe:arquillian-core:pom:1.1.13.5:test
[INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-depchain:pom:1.2.6:test
[INFO] |  |  |  \- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:test
[INFO] |  |  \- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-depchain:pom:3.0.0-alpha-4:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api:jar:3.0.0-alpha-4:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi:jar:3.0.0-alpha-4:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven:jar:3.0.0-alpha-4:test
[INFO] |  |     |  \- org.apache.maven:maven-model:jar:3.3.9:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven:jar:3.0.0-alpha-4:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven-archive:jar:3.0.0-alpha-4:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven:jar:3.0.0-alpha-4:test
[INFO] |  |     |  +- org.eclipse.aether:aether-api:jar:1.0.2.v20150114:test
[INFO] |  |     |  +- org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:test
[INFO] |  |     |  +- org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:test
[INFO] |  |     |  +- org.eclipse.aether:aether-util:jar:1.0.2.v20150114:test
[INFO] |  |     |  +- org.eclipse.aether:aether-connector-basic:jar:1.0.2.v20150114:test
[INFO] |  |     |  +- org.eclipse.aether:aether-transport-wagon:jar:1.0.2.v20150114:test
[INFO] |  |     |  +- org.apache.maven:maven-aether-provider:jar:3.3.9:test
[INFO] |  |     |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:1.6:test
[INFO] |  |     |  +- org.apache.maven:maven-model-builder:jar:3.3.9:test
[INFO] |  |     |  |  +- org.apache.maven:maven-artifact:jar:3.3.9:test
[INFO] |  |     |  |  \- org.apache.maven:maven-builder-support:jar:3.3.9:test
[INFO] |  |     |  +- org.apache.maven:maven-repository-metadata:jar:3.3.9:test
[INFO] |  |     |  +- org.apache.maven:maven-settings:jar:3.3.9:test
[INFO] |  |     |  +- org.apache.maven:maven-settings-builder:jar:3.3.9:test
[INFO] |  |     |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:test
[INFO] |  |     |  +- org.codehaus.plexus:plexus-utils:jar:3.0.22:test
[INFO] |  |     |  +- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:test
[INFO] |  |     |  |  \- org.sonatype.plexus:plexus-cipher:jar:1.7:test
[INFO] |  |     |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.10:test
[INFO] |  |     |  +- org.apache.maven.wagon:wagon-file:jar:2.10:test
[INFO] |  |     |  |  \- commons-lang:commons-lang:jar:2.6:test
[INFO] |  |     |  \- org.apache.maven.wagon:wagon-http-lightweight:jar:2.10:test
[INFO] |  |     |     \- org.apache.maven.wagon:wagon-http-shared:jar:2.10:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven-archive:jar:3.0.0-alpha-4:test
[INFO] |  |     |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven-archive:jar:3.0.0-alpha-4:test
[INFO] |  |     |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.2:test
[INFO] |  |     |  |  +- javax.enterprise:cdi-api:jar:1.0:test
[INFO] |  |     |  |  |  +- javax.annotation:jsr250-api:jar:1.0:test
[INFO] |  |     |  |  |  \- javax.inject:javax.inject:jar:1:test
[INFO] |  |     |  |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.2:test
[INFO] |  |     |  \- org.codehaus.plexus:plexus-compiler-javac:jar:2.7:test
[INFO] |  |     |     \- org.codehaus.plexus:plexus-compiler-api:jar:2.7:test
[INFO] |  |     +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven-embedded:jar:3.0.0-alpha-4:test
[INFO] |  |     |  \- org.apache.maven.shared:maven-invoker:jar:2.2:test
[INFO] |  |     \- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven-embedded:jar:3.0.0-alpha-4:test
[INFO] |  \- org.jboss.arquillian.junit:arquillian-junit-container:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.junit:arquillian-junit-core:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.test:arquillian-test-api:jar:1.1.13.Final:test
[INFO] |     |  \- org.jboss.arquillian.core:arquillian-core-api:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.test:arquillian-test-spi:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.core:arquillian-core-impl-base:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.test:arquillian-test-impl-base:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.container:arquillian-container-impl-base:jar:1.1.13.Final:test
[INFO] |     \- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:test
[INFO] +- org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-spi:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.arquillian.core:arquillian-core-spi:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.arquillian.config:arquillian-config-api:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.arquillian.config:arquillian-config-impl-base:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:test
[INFO] |  |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:jar:2.0.0:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-api:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-spi:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-impl-base:jar:1.1.13.Final:test
[INFO] |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-spi:jar:2.0.0:test
[INFO] +- org.arquillian.universe:arquillian-graphene:pom:1.1.13.5:test
[INFO] |  +- org.arquillian.universe:arquillian-drone:pom:1.1.13.5:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-api:jar:3.4.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-java:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.4.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.4.0:test
[INFO] |  |  |  +- cglib:cglib-nodep:jar:3.2.4:test
[INFO] |  |  |  +- org.apache.commons:commons-exec:jar:1.3:test
[INFO] |  |  |  +- org.apache.commons:commons-lang3:jar:3.4:test
[INFO] |  |  |  +- commons-codec:commons-codec:jar:1.10:test
[INFO] |  |  |  +- commons-logging:commons-logging:jar:1.2:test
[INFO] |  |  |  +- org.w3c.css:sac:jar:1.3:test
[INFO] |  |  |  +- net.sourceforge.cssparser:cssparser:jar:0.9.22:test
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.8.0:test
[INFO] |  |  |  +- net.sourceforge.htmlunit:htmlunit:jar:2.26:test
[INFO] |  |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.26:test
[INFO] |  |  |  +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.25:test
[INFO] |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:test
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.6:test
[INFO] |  |  |  +- org.apache.httpcomponents:httpmime:jar:4.5.3:test
[INFO] |  |  |  +- org.eclipse.jetty:jetty-io:jar:9.4.1.v20170120:test
[INFO] |  |  |  +- org.eclipse.jetty:jetty-util:jar:9.4.1.v20170120:test
[INFO] |  |  |  +- net.java.dev.jna:jna:jar:4.1.0:test
[INFO] |  |  |  +- net.java.dev.jna:jna-platform:jar:4.1.0:test
[INFO] |  |  |  +- com.codeborne:phantomjsdriver:jar:1.4.1:test
[INFO] |  |  |  +- org.seleniumhq.selenium:htmlunit-driver:jar:2.26:test
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:test
[INFO] |  |  |  +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.3.v20170317:test
[INFO] |  |  |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.3.v20170317:test
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-client:jar:9.4.3.v20170317:test
[INFO] |  |  |  |     \- org.eclipse.jetty:jetty-http:jar:9.4.3.v20170317:test
[INFO] |  |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.3.v20170317:test
[INFO] |  |  |  +- xalan:serializer:jar:2.7.2:test
[INFO] |  |  |  +- xalan:xalan:jar:2.7.2:test
[INFO] |  |  |  \- xerces:xercesImpl:jar:2.11.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-support:jar:3.4.0:test
[INFO] |  |  \- org.jboss.arquillian.extension:arquillian-drone-webdriver-depchain:pom:2.3.1:test
[INFO] |  |     \- org.jboss.arquillian.extension:arquillian-drone-impl:jar:2.3.1:test
[INFO] |  \- org.jboss.arquillian.graphene:graphene-webdriver:pom:2.2.0:test
[INFO] |     +- org.jboss.arquillian.graphene:graphene-webdriver-api:jar:2.2.0:test
[INFO] |     +- org.jboss.arquillian.graphene:graphene-webdriver-spi:jar:2.2.0:test
[INFO] |     \- org.jboss.arquillian.graphene:graphene-webdriver-impl:jar:2.2.0:test
[INFO] |        +- cglib:cglib:jar:2.2.2:test
[INFO] |        |  \- asm:asm:jar:3.3.1:test
[INFO] |        \- org.objenesis:objenesis:jar:1.2:test
[INFO] +- org.jboss.arquillian.graphene:arquillian-browser-screenshooter:jar:2.3.0:test
[INFO] |  +- org.arquillian.extension:arquillian-recorder-screenshooter-impl-base:jar:1.1.0.Final:test
[INFO] |  |  +- org.arquillian.extension:arquillian-recorder-screenshooter-api:jar:1.1.0.Final:test
[INFO] |  |  |  +- org.arquillian.extension:arquillian-recorder-api:jar:1.1.0.Final:test
[INFO] |  |  |  +- org.arquillian.extension:arquillian-recorder-reporter-api:jar:1.1.0.Final:test
[INFO] |  |  |  |  \- org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.5.1:test
[INFO] |  |  |  |     +- org.eclipse.persistence:org.eclipse.persistence.core:jar:2.5.1:test
[INFO] |  |  |  |     |  \- org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.5.1:test
[INFO] |  |  |  |     \- org.eclipse.persistence:org.eclipse.persistence.antlr:jar:2.5.1:test
[INFO] |  |  |  \- com.jhlabs:filters:jar:2.0.235:test
[INFO] |  |  +- org.arquillian.extension:arquillian-recorder-reporter-impl:jar:1.1.0.Final:test
[INFO] |  |  |  +- org.arquillian.extension:arquillian-recorder-reporter-spi:jar:1.1.0.Final:test
[INFO] |  |  |  \- org.arquillian.extension:arquillian-recorder-video-api:jar:1.1.0.Final:test
[INFO] |  |  \- commons-io:commons-io:jar:1.3.2:test
[INFO] |  +- org.arquillian.extension:arquillian-recorder-screenshooter-spi:jar:1.1.0.Final:test
[INFO] |  |  \- org.arquillian.extension:arquillian-recorder-spi:jar:1.1.0.Final:test
[INFO] |  \- org.jboss.arquillian.extension:arquillian-drone-webdriver:jar:2.3.1:test
[INFO] |     +- org.jboss.arquillian.extension:arquillian-drone-api:jar:2.3.1:test
[INFO] |     +- org.jboss.arquillian.extension:arquillian-drone-spi:jar:2.3.1:test
[INFO] |     +- org.jboss.arquillian.extension:arquillian-drone-configuration:jar:2.3.1:test
[INFO] |     +- org.arquillian.spacelift:arquillian-spacelift:jar:1.0.0.Alpha9:test
[INFO] |     |  +- org.arquillian.spacelift:arquillian-spacelift-api:jar:1.0.0.Alpha9:test
[INFO] |     |  \- org.apache.commons:commons-compress:jar:1.8.1:test
[INFO] |     +- org.jsoup:jsoup:jar:1.8.3:test
[INFO] |     \- org.awaitility:awaitility:jar:3.0.0:test
[INFO] |        \- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- org.arquillian.universe:arquillian-chameleon:pom:1.1.13.5:test
[INFO] |  \- org.arquillian.container:arquillian-container-chameleon:jar:1.0.0.Beta2:test
[INFO] |     +- org.arquillian.container:arquillian-chameleon-container-model:jar:1.0.0.Beta2:test
[INFO] |     +- org.jboss.arquillian.testenricher:arquillian-testenricher-ejb:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.testenricher:arquillian-testenricher-resource:jar:1.1.13.Final:test
[INFO] |     +- org.jboss.arquillian.testenricher:arquillian-testenricher-cdi:jar:1.1.13.Final:test
[INFO] |     \- org.jboss.arquillian.testenricher:arquillian-testenricher-initialcontext:jar:1.1.13.Final:test
[INFO] +- com.google.guava:guava:jar:21.0:test
[INFO] \- xml-apis:xml-apis:jar:1.4.01:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.257 s
[INFO] Finished at: 2017-07-25T15:25:10-03:00
[INFO] Final Memory: 22M/344M
[INFO] ------------------------------------------------------------------------

```

**Comment by MatousJobanek** [comment]
Hi, 
according to this page: https://chromedriver.storage.googleapis.com/2.31/notes.txt
ChromeDriver 2.30 & 2.31 are compatible with Chrome versions v58-60. 
ChromeDriver 2.29 is compatible with v56-58, so if you are using an older version of Chrome, then that is the reason for the error. 
You need to update your version of Chrome or use an older version of ChromeDriver compatible with your browser.

**Comment by rmpestano** [comment]
Yeap, I've assumed my chrome was on latest version but not. Thank you @MatousJobanek 

I need to pay more attention on error messages :laughing:
