### ISSUE TITLE
Graphene features does not work in Firefox.

### ISSUE THREAD

**Issue by vinsguru** [arquillian/arquillian-extension-drone#121]
Finding element by using JQuery selector throws error in Firefox. (Works great in Chrome).

`ByJQuery.selector("div.myclass");`

```
Caused by: java.lang.IllegalStateException: Can't invoke the javacript org.jboss.arquillian.graphene.findby.JQuerySearchContext#findElements()
	at org.jboss.arquillian.graphene.javascript.DefaultExecutionResolver.execute(DefaultExecutionResolver.java:84)
	at org.jboss.arquillian.graphene.javascript.JSInterfaceHandler.intercept(JSInterfaceHandler.java:58)
	at org.jboss.arquillian.graphene.cglib.ClassImposterizer$ClassWithSuperclassToWorkAroundCglibBug$$EnhancerByGraphene$$8b8b57ce.findElements(<generated>)
	at org.jboss.arquillian.graphene.findby.ByJQueryImpl.findElements(ByJQueryImpl.java:65)
	... 95 more
Caused by: java.lang.RuntimeException: org.openqa.selenium.JavascriptException: ReferenceError: Graphene is not defined
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'VINSWW-4SQXJS1', ip: '10.11.12.113', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusableRemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 57.0.1, droneAugmented: ReusableRemoteWebDriver: fi..., javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 385, moz:profile: /tmp/rust_mozprofile.gNTNLL..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.2.0-35-generic, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 13a8bbbb-b589-41c7-88bc-06e76e58c756
	at org.jboss.arquillian.graphene.javascript.JavaScriptUtils.execute(JavaScriptUtils.java:49)
	at org.jboss.arquillian.graphene.javascript.DefaultExecutionResolver.executeScriptForCall(DefaultExecutionResolver.java:139)
	at org.jboss.arquillian.graphene.javascript.DefaultExecutionResolver.execute(DefaultExecutionResolver.java:78)
```

**Comment by vinsguru** [comment]
It does not seem to do anything with JQuerySelector.

instead where I try to use Graphene features I get error in Firefox 57. 

```
java.lang.IllegalStateException: The Graphene runtime isn't initialized.
	at org.jboss.arquillian.graphene.GrapheneRuntime.getInstance(GrapheneRuntime.java:116)
	at org.jboss.arquillian.graphene.Graphene.instance(Graphene.java:323)
	at org.jboss.arquillian.graphene.Graphene.waitGui(Graphene.java:216)
	at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor.intercept(StaleElementInterceptor.java:43)
	at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
	at org.jboss.arquillian.graphene.intercept.InterceptorBuilder$2.intercept(InterceptorBuilder.java:139)
	at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at com.sun.proxy.$Proxy32.isDisplayed(Unknown Source)
	at org.jboss.arquillian.graphene.GrapheneElementImpl.isDisplayed(GrapheneElementImpl.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
	at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
	at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
	at com.sun.proxy.$Proxy33.isDispl
```ayed(Unknown Source)

**Comment by jagdeepjain** [comment]
anyone looking into this yet?

**Comment by lprimak** [comment]
Please retest and reopen if necessary (With Graphen 3.0.0-alpha.4)
