### ISSUE TITLE
Qualified driver fails on any call with IllegalStateException

### ISSUE THREAD

**Issue by AndyGee** [arquillian/arquillian-extension-drone#131]
@ClassScoped
    @Isam
    @Drone
    private WebDriver isam;

    public void open() {
        isam.get("http://localhost:9999/tag");
    }

java.lang.IllegalStateException: There is an browser interleaving of org.jboss.arquillian.drone.api.annotation.Default and com.tomitribe.pxc.Isam.
        at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:57)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)

**Comment by AndyGee** [comment]
Triaged - The WebDriver above is in a Page object. This page object was being injected into the test class, but was not using the @Isam qualifier. This caused the page object to be seeded with a @Default driver. The page is now injected with the correct qualifier, and this now works as expected.
...
@Isam
@Page
PageIsam pageIsam;
