### ISSUE TITLE
Chrome driver 64-bit might not be available for Windows

### ISSUE THREAD

**Issue by mabartos** [arquillian/arquillian-extension-drone#300]
##### Issue Overview

It's not possible to fetch the Chrome driver for Windows machines due to the fact, there's only provided 32-bit version of the driver and Drone is seeking for the 64-bit version. However, the 32-bit version should be compatible to 64-bit browsers and machines [1].

[1] https://bugs.chromium.org/p/chromedriver/issues/detail?id=1797#c1

#### Solution
Solution for that would be that if the 64-bit WebDriver for Windows is not found, it'd try to fetch the 32-bit version of it.

#### Provided Chrome Drivers

```
 <Contents>
<Key>96.0.4664.18/chromedriver_linux64.zip</Key>
<Generation>1635142532134035</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2021-10-25T06:15:32.167Z</LastModified>
<ETag>"e8b409daf617e69cbf9a325606d65375"</ETag>
<Size>9981693</Size>
</Contents>
<Contents>
<Key>96.0.4664.18/chromedriver_mac64.zip</Key>
<Generation>1635142534339256</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2021-10-25T06:15:34.371Z</LastModified>
<ETag>"6ce0a3b645e8bc4d0baf4d21fd0fa902"</ETag>
<Size>8232190</Size>
</Contents>
<Contents>
<Key>96.0.4664.18/chromedriver_mac64_m1.zip</Key>
<Generation>1635142536513349</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2021-10-25T06:15:36.546Z</LastModified>
<ETag>"87b3bf1f8bac7df115930330b3eaf6a9"</ETag>
<Size>7787623</Size>
</Contents>
<Contents>
<Key>96.0.4664.18/chromedriver_win32.zip</Key>
<Generation>1635142538618432</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2021-10-25T06:15:38.651Z</LastModified>
<ETag>"5201972f802fcb345fc93cb4ee117683"</ETag>
<Size>6073766</Size>
</Contents>
```

#### Error
```
Caused by: org.jboss.arquillian.drone.webdriver.binary.downloading.source.MissingBinaryException: There wasn't found any binary with the key matching regex \Q96.0.4664.45/chromedriver_win64.zip\E in the storage: https://chromedriver.storage.googleapis.com/
	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.XmlStorageSource.getReleaseForVersion(XmlStorageSource.java:157)
	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.XmlStorageSource.getLatestRelease(XmlStorageSource.java:82)
	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.XmlStorageSource.getLatestRelease(XmlStorageSource.java:75)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.downloadAndPrepare(AbstractBinaryHandler.java:175)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:61)
	... 12 more
```

**Comment by jomarko** [comment]
@bartoszmajsak @mabartos hello, I see the issue is closed, is the fix included in `3.0.0-alpha.2`? Asking as I can still reproduce it with that version. Is some configuration change also needed please? Currently in my arquillian.xml I have entry like:
```
<property name="chromeDriverVersion">${chrome.driver.version:96.0.4664.45}</property>
```

Do I need to force 32 over 64 somehow?

**Comment by bartoszmajsak** [comment]
Can you share error message?

**Comment by jomarko** [comment]
sure @bartoszmajsak 

```
java.lang.RuntimeException: Could not create statement
	at org.jboss.arquillian.junit.Arquillian.methodBlock(Arquillian.java:321)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:174)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:376)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:185)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:140)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.IllegalStateException: Something bad happened when Drone was trying to download and prepare a binary. For more information see the cause.
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:63)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.getCapabilities(ChromeDriverFactory.java:106)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:80)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:42)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jboss.arquillian.drone.webdriver.binary.downloading.source.MissingBinaryException: There wasn't found any binary with the key matching regex \Q96.0.4664.45/chromedriver_win64.zip\E in the storage: https://chromedriver.storage.googleapis.com/
	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.XmlStorageSource.getReleaseForVersion(XmlStorageSource.java:162)
	at org.jboss.arquillian.drone.webdriver.binary.downloading.source.XmlStorageSource.getReleaseForVersion(XmlStorageSource.java:145)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.downloadAndPrepare(AbstractBinaryHandler.java:170)
	at org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler.checkAndSetBinary(AbstractBinaryHandler.java:61)
```

**Comment by jomarko** [comment]
ok I think I understand now, maybe few more changes are needed in `public ExternalBinary getReleaseForVersion(String requiredVersion, Architecture architecture)` looking on #301 can open PR later

**Comment by bartoszmajsak** [comment]
Yes, it seems we have a bug, as the binary for 32bit is there. Thanks for looking at it!
