### ISSUE TITLE
Chrome version - 116 is not getting launched through Drone.

### ISSUE THREAD

**Issue by sendkrishna** [arquillian/arquillian-extension-drone#405]
Hi Team,

I have implemented arquillian framework to create an automation framework. Recently, Chrome got updated to version 116 and after that I have found that chrome is not getting launched through Drone.

Mentioned below is the trace that I have got during the execution. Can anyone pls resolve this issue?

Please let me know if anyone is having work around for this issue?

Caused by: org.jboss.arquillian.graphene.enricher.exception.PageFragmentInitializationException: org.jboss.arquillian.graphene.enricher.exception.PageFragmentInitializationException: java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(Capabilities): org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'XXXXXX', ip: 'XXXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	GetHandleVerifier [0x00F0A813+48355]
	(No symbol) [0x00E9C4B1]
	(No symbol) [0x00DA5358]
	(No symbol) [0x00DC61AC]
	(No symbol) [0x00DC1EF3]
	(No symbol) [0x00DC0579]
	(No symbol) [0x00DF0C55]
	(No symbol) [0x00DF093C]
	(No symbol) [0x00DEA536]
	(No symbol) [0x00DC82DC]
	(No symbol) [0x00DC93DD]
	GetHandleVerifier [0x0116AABD+2539405]
	GetHandleVerifier [0x011AA78F+2800735]
	GetHandleVerifier [0x011A456C+2775612]
	GetHandleVerifier [0x00F951E0+616112]
	(No symbol) [0x00EA5F8C]
	(No symbol) [0x00EA2328]
	(No symbol) [0x00EA240B]
	(No symbol) [0x00E94FF7]
	BaseThreadInitThunk [0x75AF00C9+25]
	RtlGetAppContainerNamedObjectPath [0x77817B1E+286]
	RtlGetAppContainerNamedObjectPath [0x77817AEE+238]

	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.createPageFragment(PageFragmentEnricher.java:178)
	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.setupPageFragment(PageFragmentEnricher.java:231)
	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.enrich(PageFragmentEnricher.java:86)
	at org.jboss.arquillian.graphene.enricher.AbstractSearchContextEnricher.enrichRecursively(AbstractSearchContextEnricher.java:73)
	at org.jboss.arquillian.graphene.enricher.PageObjectEnricher.setupPage(PageObjectEnricher.java:148)
	at org.jboss.arquillian.graphene.enricher.PageObjectEnricher.createPage(PageObjectEnricher.java:101)
	... 63 more
Caused by: org.jboss.arquillian.graphene.enricher.exception.PageFragmentInitializationException: java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(Capabilities): org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'KJHA-HP440-R', ip: '10.212.136.53', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	GetHandleVerifier [0x00F0A813+48355]
	(No symbol) [0x00E9C4B1]
	(No symbol) [0x00DA5358]
	(No symbol) [0x00DC61AC]
	(No symbol) [0x00DC1EF3]
	(No symbol) [0x00DC0579]
	(No symbol) [0x00DF0C55]
	(No symbol) [0x00DF093C]
	(No symbol) [0x00DEA536]
	(No symbol) [0x00DC82DC]
	(No symbol) [0x00DC93DD]
	GetHandleVerifier [0x0116AABD+2539405]
	GetHandleVerifier [0x011AA78F+2800735]
	GetHandleVerifier [0x011A456C+2775612]
	GetHandleVerifier [0x00F951E0+616112]
	(No symbol) [0x00EA5F8C]
	(No symbol) [0x00EA2328]
	(No symbol) [0x00EA240B]
	(No symbol) [0x00E94FF7]
	BaseThreadInitThunk [0x75AF00C9+25]
	RtlGetAppContainerNamedObjectPath [0x77817B1E+286]
	RtlGetAppContainerNamedObjectPath [0x77817AEE+238]

	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.createPageFragment(PageFragmentEnricher.java:178)
	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.setupPageFragment(PageFragmentEnricher.java:231)
	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.enrich(PageFragmentEnricher.java:86)
	at org.jboss.arquillian.graphene.enricher.AbstractSearchContextEnricher.enrichRecursively(AbstractSearchContextEnricher.java:73)
	at org.jboss.arquillian.graphene.enricher.PageFragmentEnricher.createPageFragment(PageFragmentEnricher.java:163)
	... 68 more
Caused by: java.lang.RuntimeException: Unable to instantiate Drone via org.openqa.selenium.chrome.ChromeDriver(Capabilities): org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'XXXXXX', ip: 'XXXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	GetHandleVerifier [0x00F0A813+48355]
	(No symbol) [0x00E9C4B1]
	(No symbol) [0x00DA5358]
	(No symbol) [0x00DC61AC]
	(No symbol) [0x00DC1EF3]
	(No symbol) [0x00DC0579]
	(No symbol) [0x00DF0C55]
	(No symbol) [0x00DF093C]
	(No symbol) [0x00DEA536]
	(No symbol) [0x00DC82DC]
	(No symbol) [0x00DC93DD]
	GetHandleVerifier [0x0116AABD+2539405]
	GetHandleVerifier [0x011AA78F+2800735]
	GetHandleVerifier [0x011A456C+2775612]
	GetHandleVerifier [0x00F951E0+616112]
	(No symbol) [0x00EA5F8C]
	(No symbol) [0x00EA2328]
	(No symbol) [0x00EA240B]
	(No symbol) [0x00E94FF7]
	BaseThreadInitThunk [0x75AF00C9+25]
	RtlGetAppContainerNamedObjectPath [0x77817B1E+286]
	RtlGetAppContainerNamedObjectPath [0x77817AEE+238]

	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:166)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:82)
	at org.jboss.arquillian.drone.webdriver.factory.ChromeDriverFactory.createInstance(ChromeDriverFactory.java:42)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:127)
	at org.jboss.arquillian.drone.webdriver.factory.WebDriverFactory.createInstance(WebDriverFactory.java:38)
	at org.jboss.arquillian.drone.impl.DroneConfigurator$1.createInstance(DroneConfigurator.java:112)
	at org.jboss.arquillian.drone.impl.CachingCallableImpl.call(CachingCallableImpl.java:44)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'XXXXXX', ip: 'XXXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.19'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	GetHandleVerifier [0x00F0A813+48355]
	(No symbol) [0x00E9C4B1]
	(No symbol) [0x00DA5358]
	(No symbol) [0x00DC61AC]
	(No symbol) [0x00DC1EF3]
	(No symbol) [0x00DC0579]
	(No symbol) [0x00DF0C55]
	(No symbol) [0x00DF093C]
	(No symbol) [0x00DEA536]
	(No symbol) [0x00DC82DC]
	(No symbol) [0x00DC93DD]
	GetHandleVerifier [0x0116AABD+2539405]
	GetHandleVerifier [0x011AA78F+2800735]
	GetHandleVerifier [0x011A456C+2775612]
	GetHandleVerifier [0x00F951E0+616112]
	(No symbol) [0x00EA5F8C]
	(No symbol) [0x00EA2328]
	(No symbol) [0x00EA240B]
	(No symbol) [0x00E94FF7]
	BaseThreadInitThunk [0x75AF00C9+25]
	RtlGetAppContainerNamedObjectPath [0x77817B1E+286]
	RtlGetAppContainerNamedObjectPath [0x77817AEE+238]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:147)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.arquillian.drone.webdriver.factory.SecurityActions.newInstance(SecurityActions.java:144)
	... 11 more

Thanks!

**Comment by lprimak** [comment]
Hi,
you can set the path to the chrome driver binary via system properties, and not rely on auto-downloads. Please see drone docs on how to do that.

**Comment by sendkrishna** [comment]
> Hi, you can set the path to the chrome driver binary via system properties, and not rely on auto-downloads. Please see drone docs on how to do that.

Thanks that worked!
